// Genprops extracts connection property names (and metadata) from go-sql-spanner's
// connection_properties.go for docs. Run: go run ./tools/genprops -out <file>
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type moduleInfo struct {
	Path    string `json:"Path"`
	Version string `json:"Version"`
	Dir     string `json:"Dir"`
}

type prop struct {
	Name        string
	Context     string // e.g. ContextStartup
	Description string
	ReadOnly    bool
}

func main() {
	outPath := flag.String("out", "docs/generated/connection-properties.generated.md", "output markdown path")
	flag.Parse()

	mod, err := goListModule("github.com/googleapis/go-sql-spanner")
	if err != nil {
		fmt.Fprintf(os.Stderr, "genprops: %v\n", err)
		os.Exit(1)
	}
	srcPath := filepath.Join(mod.Dir, "connection_properties.go")
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, srcPath, nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "genprops: parse %s: %v\n", srcPath, err)
		os.Exit(1)
	}

	var props []prop
	ast.Inspect(f, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		name := callName(call.Fun)
		switch name {
		case "createConnectionProperty":
			if len(call.Args) < 6 {
				return true
			}
			nm, ok := stringExpr(call.Args[0])
			if !ok {
				return true
			}
			desc, _ := descriptionExpr(call.Args[1])
			ctx := contextFromExpr(call.Args[5])
			props = append(props, prop{Name: nm, Description: desc, Context: ctx, ReadOnly: false})
		case "createReadOnlyConnectionProperty":
			if len(call.Args) < 6 {
				return true
			}
			nm, ok := stringExpr(call.Args[0])
			if !ok {
				return true
			}
			desc, _ := descriptionExpr(call.Args[1])
			ctx := contextFromExpr(call.Args[5])
			props = append(props, prop{Name: nm, Description: desc, Context: ctx, ReadOnly: true})
		default:
			return true
		}
		return true
	})

	sort.Slice(props, func(i, j int) bool { return props[i].Name < props[j].Name })

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "<!-- Code generated by tools/genprops; DO NOT EDIT. -->\n")
	fmt.Fprintf(&buf, "<!-- Source: %s @ %s -->\n\n", mod.Path, mod.Version)
	fmt.Fprintf(&buf, "## Connection properties (generated)\n\n")
	fmt.Fprintf(&buf, "The table below is **generated by static analysis** of **`%s`** `connection_properties.go`. "+
		"Descriptions are the upstream English text as-is. For a hand-written summary and grouping, see [go-sql-spanner-dsn.md](../go-sql-spanner-dsn.md).\n\n",
		mod.Path)
	fmt.Fprintf(&buf, "| Property (DSN / SHOW·SET) | connectionstate.Context | Read-only | Description (upstream) |\n")
	fmt.Fprintf(&buf, "|------------------------------|-------------------------|--------------|------------------|\n")
	for _, p := range props {
		ro := ""
		if p.ReadOnly {
			ro = "yes"
		}
		desc := strings.ReplaceAll(p.Description, "|", "\\|")
		desc = strings.ReplaceAll(desc, "\n", " ")
		if len(desc) > 300 {
			desc = desc[:297] + "..."
		}
		fmt.Fprintf(&buf, "| `%s` | `%s` | %s | %s |\n", p.Name, p.Context, ro, desc)
	}

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "genprops: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*outPath, buf.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genprops: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "genprops: wrote %s (%d properties)\n", *outPath, len(props))
}

func goListModule(path string) (*moduleInfo, error) {
	cmd := exec.Command("go", "list", "-json", "-m", path)
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list -m %s: %w", path, err)
	}
	var m moduleInfo
	if err := json.Unmarshal(out, &m); err != nil {
		return nil, err
	}
	if m.Dir == "" {
		return nil, fmt.Errorf("empty Dir for module %s", path)
	}
	return &m, nil
}

func callName(e ast.Expr) string {
	switch x := e.(type) {
	case *ast.Ident:
		return x.Name
	case *ast.SelectorExpr:
		return x.Sel.Name
	default:
		return ""
	}
}

func stringExpr(e ast.Expr) (string, bool) {
	switch x := e.(type) {
	case *ast.BasicLit:
		if x.Kind != token.STRING {
			return "", false
		}
		s, err := strconv.Unquote(x.Value)
		if err != nil {
			return "", false
		}
		return s, true
	case *ast.BinaryExpr:
		if x.Op != token.ADD {
			return "", false
		}
		a, ok1 := stringExpr(x.X)
		b, ok2 := stringExpr(x.Y)
		if !ok1 || !ok2 {
			return "", false
		}
		return a + b, true
	default:
		return "", false
	}
}

// descriptionExpr is like stringExpr but also accepts fmt.Sprintf("...", ...) using the format string only.
func descriptionExpr(e ast.Expr) (string, bool) {
	if s, ok := stringExpr(e); ok {
		return s, true
	}
	call, ok := e.(*ast.CallExpr)
	if !ok || callName(call.Fun) != "Sprintf" || len(call.Args) == 0 {
		return "", false
	}
	return stringExpr(call.Args[0])
}

func contextFromExpr(e ast.Expr) string {
	sel, ok := e.(*ast.SelectorExpr)
	if !ok {
		return ""
	}
	return sel.Sel.Name
}
